CREATE TABLE "agent_sessions" (
    "id" UUID NOT NULL,
    "iteration_count" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);

-- #[toasty::breakpoint]

CREATE TABLE "agent_messages" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "session_id" UUID NOT NULL,
    "sequence" BIGINT NOT NULL,
    "role" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

-- #[toasty::breakpoint]

CREATE INDEX "index_agent_messages_by_session_id" ON "agent_messages" ("session_id");
