use std::{env, fs, path::PathBuf};

use midgard_agent::{
    AgentMessage, AgentRole, AgentRunEvent, AgentRunStatus, AgentSession, AgentToolCall,
    ApprovalDecision, ApprovalRecord, ApprovalStatus, PendingApproval,
};
use midgard_core::{CompletionStatus, RiskLevel};
use midgard_server::{
    AddOrganizationMemberRequest, AgentRunResponse, ApprovalResponse, CreateAuthUserRequest,
    CreateOrganizationRequest, CreateWorkspaceRequest, DashboardTone, LoginRequest, LogoutResponse,
    MiddlewareDashboardState, MiddlewareMetric, MiddlewareTimelineEvent, MiddlewareWorkload,
    PluginResponse, RunAccepted, UpdateAuthUserRequest, UpdateOrganizationMemberRequest,
    UpdateWorkspaceRequest, WorkspaceEvent, WorkspaceEventPayload, WorkspaceEventType,
    WorkspaceSnapshot,
};
use midgard_storage::{
    AuthUser, Organization, OrganizationContext, OrganizationMembership, OrganizationRole,
    UserRole, Workspace,
};
use midgard_tools::{ToolDefinition, ToolResult};
use ts_rs::{Config, TS};

#[test]
fn generated_protocol_typescript_is_current() {
    let path = protocol_path();
    let generated = protocol_typescript();

    if env::var("MIDGARD_UPDATE_PROTOCOL_TS").as_deref() == Ok("1") {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, generated).unwrap();
        return;
    }

    let current = fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        current, generated,
        "generated protocol types are stale; run `MIDGARD_UPDATE_PROTOCOL_TS=1 cargo test -p midgard-server --test type_exports`"
    );
}

fn protocol_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../midgard-web/lib/generated/protocol.ts")
}

fn protocol_typescript() -> String {
    let cfg = Config::default();
    let declarations = [
        RiskLevel::decl(&cfg),
        CompletionStatus::decl(&cfg),
        ToolDefinition::decl(&cfg),
        ToolResult::decl(&cfg),
        AgentRole::decl(&cfg),
        AgentToolCall::decl(&cfg),
        AgentMessage::decl(&cfg),
        AgentRunStatus::decl(&cfg),
        PendingApproval::decl(&cfg),
        ApprovalDecision::decl(&cfg),
        ApprovalStatus::decl(&cfg),
        ApprovalRecord::decl(&cfg),
        AgentSession::decl(&cfg),
        AgentRunEvent::decl(&cfg),
        UserRole::decl(&cfg),
        AuthUser::decl(&cfg),
        LoginRequest::decl(&cfg),
        CreateAuthUserRequest::decl(&cfg),
        UpdateAuthUserRequest::decl(&cfg),
        LogoutResponse::decl(&cfg),
        OrganizationRole::decl(&cfg),
        Organization::decl(&cfg),
        OrganizationMembership::decl(&cfg),
        Workspace::decl(&cfg),
        OrganizationContext::decl(&cfg),
        CreateOrganizationRequest::decl(&cfg),
        CreateWorkspaceRequest::decl(&cfg),
        UpdateWorkspaceRequest::decl(&cfg),
        AddOrganizationMemberRequest::decl(&cfg),
        UpdateOrganizationMemberRequest::decl(&cfg),
        PluginResponse::decl(&cfg),
        RunAccepted::decl(&cfg),
        AgentRunResponse::decl(&cfg),
        ApprovalResponse::decl(&cfg),
        DashboardTone::decl(&cfg),
        MiddlewareMetric::decl(&cfg),
        MiddlewareWorkload::decl(&cfg),
        MiddlewareTimelineEvent::decl(&cfg),
        MiddlewareDashboardState::decl(&cfg),
        WorkspaceSnapshot::decl(&cfg),
        WorkspaceEventType::decl(&cfg),
        WorkspaceEventPayload::decl(&cfg),
        WorkspaceEvent::decl(&cfg),
    ];

    let declarations = declarations
        .into_iter()
        .map(|declaration| format!("export {declaration}"))
        .collect::<Vec<_>>()
        .join("\n\n");

    format!(
        "/* eslint-disable */\n/* @generated by ts-rs. Do not edit manually. */\n\n{}\n",
        declarations
    )
}
